### ISSUE TITLE
Make the button insensitive while either (or both) entries are blank

### ISSUE THREAD

**Issue by ryonakano** [lainsce/beemy#3]
Hello! Thank you for your cute app :smile: 

![peek 2018-09-24 19-55](https://user-images.githubusercontent.com/26003928/45948787-62030e80-c034-11e8-864c-9376f52dc050.gif)

At the moment the red circle button (`color_button_action`) seems to be always sensitive. I think it should be insensitive while either (or both) entries are blank, because the users may click before they fill the entries and might get confused.

With Beemy 1.0.1, on Juno Beta2

**Comment by lainsce** [comment]
Fixing it when my midterms are over (2018.09.29)

**Comment by lainsce** [comment]
Fixed now.

**Comment by NathanBnm** [comment]
@lainsce actually it's still not working when you fill only one entry. I noticed that when I updated translations.
